name: CI/CD using github actions & docker

on:
    push:
        branches: ["#47-build/deployment_automation"]
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Install dependencies
              run: |
                  cd server
                  npm install

            - name: env file create
              run: |
                  cd server
                  echo "SSH_HOST=$SSH_HOST" >> .env
                  echo "SSH_PORT=$SSH_PORT" >> .env
                  echo "SSH_USER=$SSH_USER" >> .env
                  echo "SSH_PASSWORD=$SSH_PASSWORD" >> .env
                  echo "DB_USERNAME=$DB_USERNAME" >> .env
                  echo "DB_PASSWORD=$DB_PASSWORD" >> .env
                  echo "DB_NAME=$DB_NAME" >> .env
                  echo "DB_HOST=$DB_HOST" >> .env
                  cat .env
              env:
                  SSH_HOST: ${{ secrets.SSH_HOST }}
                  SSH_PORT: ${{ secrets.SSH_PORT }}
                  SSH_USER: ${{ secrets.SSH_USER }}
                  SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
                  DB_USERNAME: ${{ secrets.DB_USERNAME }}
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                  DB_NAME: ${{ secrets.DB_NAME }}
                  DB_HOST: ${{ secrets.DB_HOST }}

            - name: Build Docker image
              run: docker build -t geomgichoi/heatpick:latest ./server

            - name: Login to Docker Hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            - name: Push Docker image to Docker Hub
              run: docker push geomgichoi/heatpick:latest

            - name: SSH into Ubuntu server and pull the latest image
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.SERVER_USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  script: |
                      docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
                      docker pull geomgichoi/heatpick
                      docker stop heatpick-container || true
                      docker rm heatpick-container || true
                      docker run -d -p 3000:3000 --name heatpick-container geomgichoi/heatpick
